///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsCompetition = 'assets/icons/competition.svg';
  static const String iconsCompetitionActive = 'assets/icons/competition_active.svg';
  static const String iconsHome = 'assets/icons/home.svg';
  static const String iconsHomeActive = 'assets/icons/home_active.svg';
  static const String iconsLoading = 'assets/icons/loading.svg';
  static const String iconsOnboard1 = 'assets/icons/onboard1.svg';
  static const String iconsOnboard2 = 'assets/icons/onboard2.svg';
  static const String iconsOnboard3 = 'assets/icons/onboard3.svg';
  static const String iconsProfile = 'assets/icons/profile.svg';
  static const String iconsProfileActive = 'assets/icons/profile_active.svg';
  static const String iconsRating = 'assets/icons/rating.svg';
  static const String iconsRatingActive = 'assets/icons/rating_active.svg';
  static const String iconsTitle = 'assets/icons/title.svg';

}
